
IF NOT EXISTS(SELECT 1 FROM sys.objects WHERE name = 'Tipo_plantilla') 
BEGIN

INSERT INTO IDIOMAS VALUES ('Inglés', 10001);
INSERT INTO IDIOMAS VALUES ('Francés', 10001);
INSERT INTO IDIOMAS VALUES ('Alemán', 10001);
INSERT INTO IDIOMAS VALUES ('Chino Mandarin', 10001);
INSERT INTO IDIOMAS VALUES ('Español', 10001);
INSERT INTO IDIOMAS VALUES ('Portuges', 10001);
END;
